### ISSUE TITLE
slice 貌似就是引用传递的呀

### ISSUE THREAD

**Issue by nerored** [cch123/golang-notes#16]
slice 原理应该和c++的vector差不多的实现，就是传递的数组内存的首指针，等同于引用传递吧，然后扩容的话，就算不传递，append后的结果你不赋值给原slice，也不会产生影响。只是一点疑问，希望得到回复

**Comment by cch123** [comment]
@nerored ，并不是，其实是把 sliceheader 展开成 addr len cap 三个值使用的

如果你在函数内部使这个传入的 slice 发生了扩容，那原来的 slice 和函数内的就是两了

我个人觉得这个其实是 Go 类型设计上没做好的地方。。。

**Comment by cch123** [comment]
```go
~/test ❯❯❯ cat sl.go
package main

import "fmt"
import "runtime/debug"

func main() {
	var a = []int{1, 2, 3}
	sliceAsParam(a)
	fmt.Println(a)
}

func sliceAsParam(sl []int) {
	debug.PrintStack()
	sl = append(sl, 4)
	sl = append(sl, 5)
	sl = append(sl, 6)
}
~/test ❯❯❯ go run -gcflags="-N -l" sl.go
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x18, 0xc000018320)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
main.sliceAsParam(0xc000018320, 0x3, 0x3)
	/Users/didi/test/sl.go:13 +0x26
main.main()
	/Users/didi/test/sl.go:8 +0x99
[1 2 3]
```

main.sliceAsParam(0xc000018320, 0x3, 0x3)，看这个地方，addr，len，cap

**Comment by nerored** [comment]
原来如此，只是表现上类似引用传递了，实际上是拆分开了，去内部做指针便宜。。多谢解答
